set up workflow files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,15 +14,43 @@ jobs:
       matrix:
         go: [ '1.18', '1.19', '1.20' ]
     steps:
-      - uses: actions/checkout@v3
-
-      - name: Setup go
-        uses: actions/setup-go@v4
+      - name: Setup Go
+        uses: actions/setup-go@v2
         with:
-          go-version: ${{ matrix.go }}
-
+          go-version: '^1.16'
       - name: Install goimports
         run: go get golang.org/x/tools/cmd/goimports
+      - name: Check code
+        uses: actions/checkout@v2
+      - run: goimports -w .
+      - name: Run go mod tidy on all modules
+        run: find . -name go.mod -execdir go mod tidy \;
+      # If there are any diffs from goimports or go mod tidy, fail.
+      - name: Verify no changes from goimports and go mod tidy.
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo 'To fix this check, run "goimports -w . && find . -name go.mod -execdir go mod tidy \;"'
+            git status # Show the files that failed to pass the check.
+            exit 1
+          fi
+      - name: go vet
+        # Use find to build all modules. '-execdir ... ;' doesn't set an exit code
+        # based on command results. So, create a file if a build fails and check
+        # if the file exists to set the right exit code.
+        run: |
+          ROOT_DIR=$(pwd) \
+          find . -name go.mod -execdir sh -c 'go vet ./... || touch $ROOT_DIR/vet_failed.txt' \; ; \
+          test ! -f vet_failed.txt
+      - name: Build code
+        # Use find to build all modules. '-execdir ... ;' doesn't set an exit code
+        # based on command results. So, create a file if a build fails and check
+        # if the file exists to set the right exit code.
+        run: |
+          ROOT_DIR=$(pwd) \
+          find . -name go.mod -execdir sh -c 'go build ./... || touch $ROOT_DIR/build_failed.txt' \; ; \
+          test ! -f build_failed.txt
+      - name: shellcheck
+        run: find . -name "*.sh" -exec shellcheck {} \;
         
       - name: Lint
         run: |
